# Generated by Django 5.2.4 on 2025-10-10 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_order_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
