# Generated by Django 5.2.4 on 2025-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_cart_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="contact",
            name="address_en",
            field=models.TextField(null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="contact",
            name="address_ru",
            field=models.TextField(null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="contact",
            name="address_uz",
            field=models.TextField(null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_uz",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="contact",
            name="working_hours_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Часы работы"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="working_hours_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Часы работы"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="working_hours_uz",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Часы работы"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="care_instructions_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Инструкции по уходу"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="care_instructions_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Инструкции по уходу"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="care_instructions_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="Инструкции по уходу"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="material_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Материал"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material_ru",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Материал"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material_uz",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Материал"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_en",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Краткое описание"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_ru",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Краткое описание"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_uz",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Краткое описание"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Текст отзыва"),
        ),
        migrations.AddField(
            model_name="review",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Текст отзыва"),
        ),
        migrations.AddField(
            model_name="review",
            name="text_uz",
            field=models.TextField(null=True, verbose_name="Текст отзыва"),
        ),
        migrations.AddField(
            model_name="review",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="review",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="review",
            name="title_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Заголовок"),
        ),
    ]
