# Generated by Django 5.2.7 on 2025-10-12 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_category_description_en_category_description_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
