# Generated by Django 5.2.4 on 2025-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_remove_category_slug_remove_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                default="Черный", max_length=50, verbose_name="Цвет"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                default="M",
                max_length=10,
                verbose_name="Размер",
            ),
        ),
    ]
