# Generated by Django 5.2.4 on 2025-10-12 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_product_color_product_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="care_instructions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="care_instructions_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="care_instructions_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="care_instructions_uz",
        ),
        migrations.RemoveField(
            model_name="product",
            name="country",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material_uz",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description_uz",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
    ]
