# Generated by Django 5.2.4 on 2025-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_remove_product_color_remove_product_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
