# Generated by Django 5.2.4 on 2025-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, verbose_name="URL"
            ),
        ),
    ]
