# Generated by Django 5.2.4 on 2025-10-14 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_remove_translation_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="care_instructions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="country",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
    ]
