# Generated by Django 5.2.4 on 2025-10-14 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_remove_product_care_instructions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
    ]
