# Generated by Django 5.2.7 on 2025-10-16 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_auto_20251014_1354"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="care_instructions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="country",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
    ]
